### ISSUE TITLE
[PE-D][Tester B] Unable to view added transaction immediately

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-3/tp#134]
![image.png](https://raw.githubusercontent.com/ncmathan/ped/main/files/ff7224a2-62e6-45dc-b1ff-8a38006b5312.png)

When a new transaction is added, it cannot be seen until another transaction is added

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ncmathan/ped#4

**Comment by cxo05** [comment]
The table does not auto scroll to bottom on transaction added. Requires feature change, not a bug.
