### ISSUE TITLE
[PE-D][Tester C] Staff: Email input is considered valid even when lacking top level domain name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-3/tp#161]
input: `editstaff 3 e/notoplevel@domain`  
output: 
![image.png](https://raw.githubusercontent.com/phiphi-tan/ped/main/files/35213e16-88b8-4299-8486-c8833e891060.png)

Emails without top level domain names (e.g. `.com`/`.org`) are still accepted as valid inputs even though it should be recognised as invalid. Might want to consider having some parser checks to ensure these are flagged out correctly

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: phiphi-tan/ped#12

**Comment by cxo05** [comment]
Requires feature change, not a bug.
