### ISSUE TITLE
[PE-D][Tester C] Export: Not allowed to rename files

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-3/tp#164]
Export files that are created (e.g. transactions.csv) are unable to be renamed before being created, and the user can only select the directory that it will lie in.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: phiphi-tan/ped#13

**Comment by cxo05** [comment]
Requires feature change, not a bug. Though we should mention it in the UG
