### ISSUE TITLE
[PE-D][Tester C] Add: Invalid Type

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W13-3/tp#180]
![image.png](https://raw.githubusercontent.com/phiphi-tan/ped/main/files/d1e602aa-e74e-408c-838a-7f6b46b72f85.png)

Warning message appears informing of invalid type but not instructing on what type is valid.

You may want to consider that invalid typing error message should display what possible types of transactions there are (so that the user is not inconvenienced).

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: phiphi-tan/ped#25

**Comment by cxo05** [comment]
Requires feature change, not a bug.
