### ISSUE TITLE
[PE-D][Tester C] Filter: Reset

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-3/tp#181]
![image.png](https://raw.githubusercontent.com/phiphi-tan/ped/main/files/ccf0b3c5-f595-484d-ad60-9d37507fda48.png)

Filter does not have any form of 'filter reset' functionality, meaning that users are unable to return back to view all transactions (i.e. removing the filter).
This is especially significant if the transactions differ in all available filter categories.

I gets that `view t` will cause the transaction filter to reset, but it's not explicitly linked to the filter function in the UG either, which creates ambiguity for the user (so for me, I could not figure out how to reset the filter until I read through the entire UG again). Consider creating some sort of `filter /all` sort of thing to be able to view all transactions, or explicitly state in the UG that `view t` removes the filter

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: phiphi-tan/ped#26

**Comment by cxo05** [comment]
Add `clearfilter` & `clearsort` commands to the UG.
